### ISSUE TITLE
ETQ utilisateur, je peux mettre des articles en favoris

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#1135]
Pour chaque article, possibilité de le mettre en favoris (en cliquant sur un coeur par ex.).
Possibilité de consulter la liste des articles mis en favoris (accès via le menu juste après la parenthèque)

**Comment by MorganeDe** [comment]
- [x] Ajout/Retrait en favoris depuis une liste d'articles (étape accueil et recherche)
- [x] Ajout/Retrait en favoris depuis le détail d'un article (étape accueil et recherche)
- [ ] Filtre par articles favoris
