### ISSUE TITLE
ETQ utilisateur, je peux paramétrer les notifications concernant les articles

### ISSUE THREAD

**Issue by christophegrassi** [SocialGouv/1000jours#1408]
- [x] création de la page générale "Paramètres de notifications"
- [x] la rendre accessible à partir du menu (après "Parenthèque") et avec un icone "engrenage" (demander à l'UX si besoin)
- [x] rajouter le bouton retour si non présent dans le header
- [x] attention à l'orientation du toggle ;)
- [x] mise en place de la partie "articles" permettant de gérer les notifs des aritcles (oui/non)
- [x] checker l'accessibilité

![image](https://user-images.githubusercontent.com/64467998/187450714-bec57665-1de0-41ff-8fb6-d7e83e47e56a.png)

**Comment by christophegrassi** [comment]
![image](https://user-images.githubusercontent.com/64467998/187450714-bec57665-1de0-41ff-8fb6-d7e83e47e56a.png)

**Comment by christophegrassi** [comment]
@alebret dans le menu burger, rajouter un "s" dans l'intitulé"Centre de notifications"
