### ISSUE TITLE
EPDS PRO - Envoyer les ressources dans le mail aux patientes

### ISSUE THREAD

**Issue by maxime-lecoq** [SocialGouv/1000jours#701]
Pour qui ? Les patients
Quoi ? Recevoir les ressources dans l'email qui leur ait addressé
Pourquoi ? Afin qu'ils aient une rappel écrit des aides possibles

**Données - corps du mail**
Bonjour,

Vous venez de passer le test EPDS. Vous trouverez ci-après votre score au test ainsi qu'une liste de structures et professionnels que vous pouvez contacter.

Score total du questionnaire EPDS : 17 / 30

<img width="618" alt="image" src="https://user-images.githubusercontent.com/82037208/134378625-455cc5fb-7362-4a60-a9b7-acf228c48c31.png">

**Critères d'acceptance**
- [ ] L'email comporte les ressources
- [ ] Les ressources sont lisibles sur web et mobile (quitte à renvoyer l'utilisateur sur une page web si besoin / plus simple)
- [ ] Le mail contient le score total obtenu au test
- [ ] le mail ne contient pas le détail des réponses

**Comment by alebret** [comment]
par contre, je ne pourrais pas faire d'accordéons dans le mail.

**Comment by maxime-lecoq** [comment]
Entièrement d'accord avec toi
